name: Compile and Release Resume
on:
  push:
    tags:
       - "**"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Get Current Date
        id: date
        run: echo "DATE=$(date +%m-%d-%Y)" >> $GITHUB_ENV

      - name: Compile PDF with Typst
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: src/main.typ
          output_paths: 'src/${{ github.ref_name }}-${{ env.DATE }}.pdf'
      
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: "**/*.pdf"
        
      
      
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: github.ref_type == 'tag'
      #   with:
      #     name: "${{ github.ref_name }} - ${{ env.DATE }}"
      #     files: src/main.pdf